const HTTP_STATUS = {
    // --2XX SUCESS CODES--
    OK :200, // SUCCESS
    CREATED : 201, // RESOURCE CREATED
    ACCEPTED : 202, // ACCEPTED REQUEST IN ASYNC OPERATION 
    NO_CONTENT : 204, // SUCCESS WITH NO REPONSE

    // 3XX REDIRECTION CODES ---
    MOVED_PERMANENTLY : 301, // MOVED PERMANENTLY
    FOUND :302, //RESOURCE TEMPORARILY MOVED.
    NOT_MODIFIED : 304,// FOR CACHED PROCESS 

    //--4XX CLIENT ERROR CODES ---
    BAD_REQUEST :400, // INVALID SYNTAX
    UNAUTHORIZED : 401, // UNAUTHORIZED CREDENTIALS
    FORBIDDEN :403, // FORBIDDEN- LACKS PERMISSIONS
    NOT_FOUND :404, // RESOURCE DOESN'T EXIST
    METHOD_NOT_ALLOWED : 405, // ACCESS METHOD NOT SUPPORTED FOR THE RESOURCE.
    CONFLICT : 409, // REQUEST CONFLICTING WITH THE CURRENT STATE OF THE RESOURCE
    TOO_MANY_REQUEST : 429, // RATE LIMITING APPLIED

    //---5XX SERVER ERROR CODES--
    INTERNAL_SERVER_ERROR: 500, // GENERIC CATCH-ALL SERVER ERROR
    NOT_IMPLEMENTED : 501, // SERVER DOESN'T SUPPORT THE REQUIRED FUNCTIONALITY
    SERVER_UNAVAILABLE : 503, // SERVER OVERLOADED OR UNDER MAINTENANCE
    GATEWAY_TIMEOUT:504, // SERVER ACTING AS GATEWAY TIMEDOUT 
};

module.exports = HTTP_STATUS;